"""add_price_tier_fields_and_store_fk

Revision ID: 4ce431613629
Revises: 20260202_1000
Create Date: 2026-02-03 07:08:56.282381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ce431613629'
down_revision: Union[str, None] = '20260202_1000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_performed_by'), table_name='audit_logs')
    op.drop_constraint(op.f('audit_logs_performed_by_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['performed_by'], ['id'])
    op.drop_index(op.f('ix_clients_created_by'), table_name='clients')
    op.drop_index(op.f('ix_delivery_team_members_team_id'), table_name='delivery_team_members')
    op.drop_constraint(op.f('uq_delivery_teams_code'), 'delivery_teams', type_='unique')
    op.drop_index(op.f('ix_delivery_teams_code'), table_name='delivery_teams')
    op.create_index(op.f('ix_delivery_teams_code'), 'delivery_teams', ['code'], unique=True)
    op.drop_constraint(op.f('uq_inventory_items_sku_id'), 'inventory_items', type_='unique')
    op.drop_index(op.f('ix_inventory_items_sku_id'), table_name='inventory_items')
    op.create_index(op.f('ix_inventory_items_sku_id'), 'inventory_items', ['sku_id'], unique=True)
    op.drop_index(op.f('ix_manufacturing_day_items_day_id'), table_name='manufacturing_day_items')
    op.drop_index(op.f('ix_manufacturing_day_items_sku_id'), table_name='manufacturing_day_items')
    op.drop_constraint(op.f('uq_manufacturing_days_plan_date'), 'manufacturing_days', type_='unique')
    op.drop_index(op.f('ix_manufacturing_days_plan_date'), table_name='manufacturing_days')
    op.create_index(op.f('ix_manufacturing_days_plan_date'), 'manufacturing_days', ['plan_date'], unique=True)
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_sku_id'), table_name='order_items')
    op.drop_index(op.f('ix_orders_client_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_by'), table_name='orders')
    op.drop_index(op.f('ix_orders_delivery_date'), table_name='orders')
    op.drop_index(op.f('ix_orders_delivery_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_delivery_team_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_sales_agent_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_store_id'), table_name='orders')
    op.add_column('price_tiers', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.drop_constraint(op.f('uq_sales_agents_code'), 'sales_agents', type_='unique')
    op.drop_index(op.f('ix_sales_agents_code'), table_name='sales_agents')
    op.create_index(op.f('ix_sales_agents_code'), 'sales_agents', ['code'], unique=True)
    op.drop_index(op.f('ix_skus_product_id'), table_name='skus')
    op.drop_constraint(op.f('uq_skus_code'), 'skus', type_='unique')
    op.drop_index(op.f('ix_skus_code'), table_name='skus')
    op.create_index(op.f('ix_skus_code'), 'skus', ['code'], unique=True)
    op.add_column('stores', sa.Column('price_tier_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'stores', 'price_tiers', ['price_tier_id'], ['id'])
    op.drop_index(op.f('ix_users_role'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.drop_column('stores', 'price_tier_id')
    op.drop_index(op.f('ix_skus_code'), table_name='skus')
    op.create_index(op.f('ix_skus_code'), 'skus', ['code'], unique=False)
    op.create_unique_constraint(op.f('uq_skus_code'), 'skus', ['code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_skus_product_id'), 'skus', ['product_id'], unique=False)
    op.drop_index(op.f('ix_sales_agents_code'), table_name='sales_agents')
    op.create_index(op.f('ix_sales_agents_code'), 'sales_agents', ['code'], unique=False)
    op.create_unique_constraint(op.f('uq_sales_agents_code'), 'sales_agents', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_column('price_tiers', 'is_active')
    op.create_index(op.f('ix_orders_store_id'), 'orders', ['store_id'], unique=False)
    op.create_index(op.f('ix_orders_sales_agent_id'), 'orders', ['sales_agent_id'], unique=False)
    op.create_index(op.f('ix_orders_delivery_team_id'), 'orders', ['delivery_team_id'], unique=False)
    op.create_index(op.f('ix_orders_delivery_status'), 'orders', ['delivery_status'], unique=False)
    op.create_index(op.f('ix_orders_delivery_date'), 'orders', ['delivery_date'], unique=False)
    op.create_index(op.f('ix_orders_created_by'), 'orders', ['created_by'], unique=False)
    op.create_index(op.f('ix_orders_client_id'), 'orders', ['client_id'], unique=False)
    op.create_index(op.f('ix_order_items_sku_id'), 'order_items', ['sku_id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.drop_index(op.f('ix_manufacturing_days_plan_date'), table_name='manufacturing_days')
    op.create_index(op.f('ix_manufacturing_days_plan_date'), 'manufacturing_days', ['plan_date'], unique=False)
    op.create_unique_constraint(op.f('uq_manufacturing_days_plan_date'), 'manufacturing_days', ['plan_date'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_manufacturing_day_items_sku_id'), 'manufacturing_day_items', ['sku_id'], unique=False)
    op.create_index(op.f('ix_manufacturing_day_items_day_id'), 'manufacturing_day_items', ['manufacturing_day_id'], unique=False)
    op.drop_index(op.f('ix_inventory_items_sku_id'), table_name='inventory_items')
    op.create_index(op.f('ix_inventory_items_sku_id'), 'inventory_items', ['sku_id'], unique=False)
    op.create_unique_constraint(op.f('uq_inventory_items_sku_id'), 'inventory_items', ['sku_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_delivery_teams_code'), table_name='delivery_teams')
    op.create_index(op.f('ix_delivery_teams_code'), 'delivery_teams', ['code'], unique=False)
    op.create_unique_constraint(op.f('uq_delivery_teams_code'), 'delivery_teams', ['code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_delivery_team_members_team_id'), 'delivery_team_members', ['delivery_team_id'], unique=False)
    op.create_index(op.f('ix_clients_created_by'), 'clients', ['created_by'], unique=False)
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_performed_by_fkey'), 'audit_logs', 'users', ['performed_by'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_audit_logs_performed_by'), 'audit_logs', ['performed_by'], unique=False)
    # ### end Alembic commands ###
